CREATE OR REPLACE VIEW QUESTIONS_VIEW AS
SELECT qa.ID                 AS "ID",
	   qc.CONTENT            AS "CONTENT",
	   qa.QUESTION_ATTRIBUTE AS "ATTRIBUTE",
	   qa.ATTRIBUTE_POSITION AS "ATTRIBUTE_POSITION",
	   qa.QUESTION_ABOUT     AS "QUESTION_ABOUT"
  FROM QUESTION_ATTRIBUTES qa
  JOIN QUESTION_CONTENT qc
	ON (qa.QUESTION_CONTENT_ID = qc.ID)
 ORDER BY qa.ID;